In [6]:
import os
import pandas as pd

In [34]:
data_pd = pd.read_csv("owid-covid-data (1).csv")
covid_deaths_pd = data_pd[['iso_code','continent','location','date','population','total_cases','new_cases','new_cases_smoothed','total_deaths','new_deaths','new_deaths_smoothed','total_cases_per_million','new_cases_per_million','new_cases_smoothed_per_million','total_deaths_per_million','new_deaths_per_million','new_deaths_smoothed_per_million','reproduction_rate','icu_patients','icu_patients_per_million','hosp_patients','hosp_patients_per_million','weekly_icu_admissions','weekly_icu_admissions_per_million','weekly_hosp_admissions','weekly_hosp_admissions_per_million']]

In [38]:
vaccination = data_pd[['iso_code','continent','location','date','new_tests','total_tests','total_tests_per_thousand','new_tests_per_thousand','new_tests_smoothed', 'new_tests_smoothed_per_thousand','positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations','people_vaccinated', 'people_fully_vaccinated', 'new_vaccinations','new_vaccinations_smoothed', 'total_vaccinations_per_hundred','people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred','new_vaccinations_smoothed_per_million', 'stringency_index','population', 'population_density', 'median_age', 'aged_65_older','aged_70_older', 'gdp_per_capita', 'extreme_poverty','cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers','male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand','life_expectancy', 'human_development_index', 'excess_mortality']]

In [45]:
vaccination.tail()

,iso_code,continent,location,date,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,...,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality
102683,ZWE,Africa,Zimbabwe,2021-07-11,4505.0,745612.0,50.166,0.303,8878.0,0.597,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN
102684,ZWE,Africa,Zimbabwe,2021-07-12,7037.0,752649.0,50.639,0.473,9364.0,0.630,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN
102685,ZWE,Africa,Zimbabwe,2021-07-13,13811.0,766460.0,51.569,0.929,9823.0,0.661,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN
102686,ZWE,Africa,Zimbabwe,2021-07-14,12604.0,779064.0,52.417,0.848,10143.0,0.682,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN
102687,ZWE,Africa,Zimbabwe,2021-07-15,NaN,NaN,NaN,NaN,NaN,NaN,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN

In [27]:
data_pd.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'new_tests', 'total_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'new_vaccinations',
       'new_vaccinations_smoothed', 'total_vaccinations_per_hundred',
       'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred',
       'new_vaccinations_smoothed_per_million', 'stringency_index',
       'population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'excess_mortality'],
      dtype='object')

In [41]:
covid_deaths_pd.to_csv('CovidDeaths.csv')

In [42]:
vaccination.to_csv('CovidVaccinations.csv')